name: deploy

on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - '!features/**'


    paths-ignore:
      - 'doc/**'
      - 'addons/**'

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT: prod

jobs:
  # Lint the Bicep file.
  lint:
    uses: ./main/.github/workflows/lint.yml

  # Deploy to the Dev environment
  deploy-dev:
    uses: ./main/.github/workflow/deploy.yml
    needs: lint
    with:
      environment: Dev
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_DEV }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID_DEV }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
  
      # Deploy to the Prod environment
  deploy-prod:
    uses: ./main/.github/workflow/deploy.yml
    needs: lint
    with:
      environment: Prod
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_PROD }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID_PROD }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID_PROD }}
  