name: deploy

on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - '!features/**'


    paths-ignore:
      - 'doc/**'
      - 'addons/**'

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT: prod

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          path: main   
      - name: Checkout ResourceModule
        uses: actions/checkout@v3
        with:
          repository: jdrepo/ResourceModules
          path: ResourceModules
      - name: Run Bicep linter
        run: az bicep build --file ./main/deploy/main.bicep
  validate:
    runs-on: ubuntu-latest
    name: Run validation job
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          path: main   
      - name: Checkout ResourceModule
        uses: actions/checkout@v3
        with:
          repository: jdrepo/ResourceModules
          path: ResourceModules
      - name: Azure CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID_DEV }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
      - name: Run preflight validation
        uses: Azure/arm-deploy@v1
        with:
          deploymentName: ${{ github.run_number }}
          failOnStdErr: false
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV}}
          region: westeurope
          template: ./main/deploy/main.bicep
          parameters: environment=${{ env.ENVIRONMENT}}
          deploymentMode: Validate
  preview:
    runs-on: ubuntu-latest
    needs: [lint, validate]
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          path: main   
      - name: Checkout ResourceModule
        uses: actions/checkout@v3
        with:
          repository: jdrepo/ResourceModules
          path: ResourceModules
      - name: Azure CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID_DEV }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
      - name: Run what-if
        uses: Azure/arm-deploy@v1
        with:
          deploymentName: ${{ github.run_number }}
          failOnStdErr: false
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV}}
          region: westeurope
          template: ./main/deploy/main.bicep
          parameters: environment=${{ env.ENVIRONMENT}}
          additionalArguments: --what-if
  deploy:
    runs-on: ubuntu-latest
    needs: [preview]
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          path: main   
      - name: Checkout ResourceModule
        uses: actions/checkout@v3
        with:
          repository: jdrepo/ResourceModules
          path: ResourceModules
      - name: Azure CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID_DEV }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          deploymentName: ${{ github.run_number }}
          failOnStdErr: false
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV}}
          region: westeurope
          template: ./main/deploy/main.bicep
          parameters: environment=${{ env.ENVIRONMENT}}
          
